//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.04 at 10:23:12 AM GMT 
//


package org.rebecalang.compiler.modelcompiler.timedrebeca.objectmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.Expression;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.ParentSuffixPrimary;


/**
 * <p>Java class for TimedRebecaParentSuffixPrimary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimedRebecaParentSuffixPrimary">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}ParentSuffixPrimary">
 *       &lt;sequence>
 *         &lt;element name="afterExpression" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression"/>
 *         &lt;element name="deadlineExpression" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimedRebecaParentSuffixPrimary", propOrder = {
    "afterExpression",
    "deadlineExpression"
})
public class TimedRebecaParentSuffixPrimary
    extends ParentSuffixPrimary
{

    @XmlElement(required = true)
    protected Expression afterExpression;
    @XmlElement(required = true)
    protected Expression deadlineExpression;

    /**
     * Gets the value of the afterExpression property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getAfterExpression() {
        return afterExpression;
    }

    /**
     * Sets the value of the afterExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setAfterExpression(Expression value) {
        this.afterExpression = value;
    }

    /**
     * Gets the value of the deadlineExpression property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getDeadlineExpression() {
        return deadlineExpression;
    }

    /**
     * Sets the value of the deadlineExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setDeadlineExpression(Expression value) {
        this.deadlineExpression = value;
    }

}
