//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 12:38:18 PM GMT 
//


package org.rebecalang.compiler.modelcompiler.probabilisticrebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.Statement;


/**
 * <p>Java class for PAltStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PAltStatement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Statement">
 *       &lt;sequence>
 *         &lt;element name="pAltStatementGroups" type="{}PAltStatementGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PAltStatement", propOrder = {
    "pAltStatementGroups"
})
public class PAltStatement
    extends Statement
{

    @XmlElement(required = true)
    protected List<PAltStatementGroup> pAltStatementGroups;

    /**
     * Gets the value of the pAltStatementGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pAltStatementGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPAltStatementGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PAltStatementGroup }
     * 
     * 
     */
    public List<PAltStatementGroup> getPAltStatementGroups() {
        if (pAltStatementGroups == null) {
            pAltStatementGroups = new ArrayList<PAltStatementGroup>();
        }
        return this.pAltStatementGroups;
    }

}
