//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 12:38:18 PM GMT 
//


package org.rebecalang.compiler.modelcompiler.probabilisticrebeca.objectmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.Expression;


/**
 * <p>Java class for ProbabilisticAlternativeValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProbabilisticAlternativeValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="probability" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression"/>
 *         &lt;element name="value" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProbabilisticAlternativeValue", namespace = "http://rebecalang.org/compiler/modelcompiler/probabilisticrebecaexpression", propOrder = {
    "probability",
    "value"
})
public class ProbabilisticAlternativeValue {

    @XmlElement(namespace = "http://rebecalang.org/compiler/modelcompiler/probabilisticrebecaexpression", required = true)
    protected Expression probability;
    @XmlElement(namespace = "http://rebecalang.org/compiler/modelcompiler/probabilisticrebecaexpression", required = true)
    protected Expression value;

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setProbability(Expression value) {
        this.probability = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Expression }
     *     
     */
    public Expression getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Expression }
     *     
     */
    public void setValue(Expression value) {
        this.value = value;
    }

}
