//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.07 at 11:39:17 AM IRST 
//


package org.rebecalang.compiler.modelcompiler.hybridrebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel.ReactiveClassDeclaration;


/**
 * <p>Java class for PhysicalClassDeclaration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalClassDeclaration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/modelcompiler/corerebeca}ReactiveClassDeclaration">
 *       &lt;sequence>
 *         &lt;element name="modeDeclarations" type="{http://rebecalang.org/compiler/modelcompiler/hybridrebeca}ModeDeclaration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalClassDeclaration", propOrder = {
    "modeDeclarations"
})
public class PhysicalClassDeclaration
    extends ReactiveClassDeclaration
{

    protected List<ModeDeclaration> modeDeclarations;

    /**
     * Gets the value of the modeDeclarations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modeDeclarations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModeDeclarations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModeDeclaration }
     * 
     * 
     */
    public List<ModeDeclaration> getModeDeclarations() {
        if (modeDeclarations == null) {
            modeDeclarations = new ArrayList<ModeDeclaration>();
        }
        return this.modeDeclarations;
    }

}
