//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.05 at 11:34:57 AM IRDT 
//


package org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimaryExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrimaryExpression">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression">
 *       &lt;sequence>
 *         &lt;element name="categoty" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Category"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimaryExpression", namespace = "http://rebecalang.org/compiler/modelcompiler/corerebecaexpression", propOrder = {
    "categoty"
})
@XmlSeeAlso({
    RebecInstantiationPrimary.class,
    TermPrimary.class,
    DotPrimary.class
})
public class PrimaryExpression
    extends Expression
{

    @XmlElement(namespace = "http://rebecalang.org/compiler/modelcompiler/corerebecaexpression", required = true)
    protected Category categoty;

    /**
     * Gets the value of the categoty property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategoty() {
        return categoty;
    }

    /**
     * Sets the value of the categoty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategoty(Category value) {
        this.categoty = value;
    }

}
