//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 03:38:36 PM IRST 
//


package org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rebecalang.org/compiler/modelcompiler/corerebeca}PackageDeclaration" minOccurs="0"/>
 *         &lt;element ref="{http://rebecalang.org/compiler/modelcompiler/corerebeca}ImportDeclaration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RebecaCode" type="{http://rebecalang.org/compiler/modelcompiler/corerebeca}RebecaCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageDeclaration",
    "importDeclaration",
    "rebecaCode"
})
@XmlRootElement(name = "RebecaModel")
public class RebecaModel {

    @XmlElement(name = "PackageDeclaration")
    protected PackageDeclaration packageDeclaration;
    @XmlElement(name = "ImportDeclaration")
    protected List<ImportDeclaration> importDeclaration;
    @XmlElement(name = "RebecaCode", required = true)
    protected RebecaCode rebecaCode;

    /**
     * Gets the value of the packageDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link PackageDeclaration }
     *     
     */
    public PackageDeclaration getPackageDeclaration() {
        return packageDeclaration;
    }

    /**
     * Sets the value of the packageDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageDeclaration }
     *     
     */
    public void setPackageDeclaration(PackageDeclaration value) {
        this.packageDeclaration = value;
    }

    /**
     * Gets the value of the importDeclaration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importDeclaration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportDeclaration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImportDeclaration }
     * 
     * 
     */
    public List<ImportDeclaration> getImportDeclaration() {
        if (importDeclaration == null) {
            importDeclaration = new ArrayList<ImportDeclaration>();
        }
        return this.importDeclaration;
    }

    /**
     * Gets the value of the rebecaCode property.
     * 
     * @return
     *     possible object is
     *     {@link RebecaCode }
     *     
     */
    public RebecaCode getRebecaCode() {
        return rebecaCode;
    }

    /**
     * Sets the value of the rebecaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RebecaCode }
     *     
     */
    public void setRebecaCode(RebecaCode value) {
        this.rebecaCode = value;
    }

}
