//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.24 at 04:06:05 PM IRDT 
//


package org.rebecalang.compiler.modelcompiler.corerebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermPrimary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TermPrimary">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}PrimaryExpression">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Label"/>
 *         &lt;element name="parentSuffixPrimary" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}ParentSuffixPrimary"/>
 *         &lt;element name="indices" type="{http://rebecalang.org/compiler/modelcompiler/corerebecaexpression}Expression" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TermPrimary", namespace = "http://rebecalang.org/compiler/modelcompiler/corerebecaexpression", propOrder = {
    "label",
    "parentSuffixPrimary",
    "indices"
})
public class TermPrimary
    extends PrimaryExpression
{

    @XmlElement(required = true)
    protected Label label;
    @XmlElement(required = true)
    protected ParentSuffixPrimary parentSuffixPrimary;
    @XmlElement(required = true)
    protected List<Expression> indices;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the parentSuffixPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link ParentSuffixPrimary }
     *     
     */
    public ParentSuffixPrimary getParentSuffixPrimary() {
        return parentSuffixPrimary;
    }

    /**
     * Sets the value of the parentSuffixPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentSuffixPrimary }
     *     
     */
    public void setParentSuffixPrimary(ParentSuffixPrimary value) {
        this.parentSuffixPrimary = value;
    }

    /**
     * Gets the value of the indices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Expression }
     * 
     * 
     */
    public List<Expression> getIndices() {
        if (indices == null) {
            indices = new ArrayList<Expression>();
        }
        return this.indices;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
