//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 11:42:38 AM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rebecalang.org/compiler/propertycompiler/corerebeca", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.rebecalang.compiler.propertycompiler.corerebeca.objectmodel;
