//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 03:53:23 PM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rebecalang.org/compiler/propertycompiler/corerebeca", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.rebecalang.compiler.propertycompiler.corerebeca.objectmodel;
