//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.04 at 09:36:51 AM IRDT 
//


package org.rebecalang.compiler.propertycompiler.corerebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyModel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rebecalang.org/compiler/propertycompiler/generalproperty}PropertyModel">
 *       &lt;sequence>
 *         &lt;element name="LTLDefinitions" type="{http://rebecalang.org/compiler/propertycompiler/corerebeca}LTLDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyModel", propOrder = {
    "ltlDefinitions"
})
public class PropertyModel
    extends org.rebecalang.compiler.propertycompiler.generalrebeca.objectmodel.PropertyModel
{

    @XmlElement(name = "LTLDefinitions")
    protected List<LTLDefinition> ltlDefinitions;

    /**
     * Gets the value of the ltlDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ltlDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLTLDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LTLDefinition }
     * 
     * 
     */
    public List<LTLDefinition> getLTLDefinitions() {
        if (ltlDefinitions == null) {
            ltlDefinitions = new ArrayList<LTLDefinition>();
        }
        return this.ltlDefinitions;
    }

}
