//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 03:53:23 PM IRDT 
//


package org.rebecalang.compiler.propertycompiler.corerebeca.objectmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Definitions" type="{http://rebecalang.org/compiler/propertycompiler/corerebeca}Definition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LTLDefinitions" type="{http://rebecalang.org/compiler/propertycompiler/corerebeca}LTLDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CTLDefinitions" type="{http://rebecalang.org/compiler/propertycompiler/corerebeca}CTLDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "definitions",
    "ltlDefinitions",
    "ctlDefinitions"
})
@XmlRootElement(name = "PropertyModel")
public class PropertyModel {

    @XmlElement(name = "Definitions")
    protected List<Definition> definitions;
    @XmlElement(name = "LTLDefinitions")
    protected List<LTLDefinition> ltlDefinitions;
    @XmlElement(name = "CTLDefinitions")
    protected List<CTLDefinition> ctlDefinitions;

    /**
     * Gets the value of the definitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the definitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Definition }
     * 
     * 
     */
    public List<Definition> getDefinitions() {
        if (definitions == null) {
            definitions = new ArrayList<Definition>();
        }
        return this.definitions;
    }

    /**
     * Gets the value of the ltlDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ltlDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLTLDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LTLDefinition }
     * 
     * 
     */
    public List<LTLDefinition> getLTLDefinitions() {
        if (ltlDefinitions == null) {
            ltlDefinitions = new ArrayList<LTLDefinition>();
        }
        return this.ltlDefinitions;
    }

    /**
     * Gets the value of the ctlDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ctlDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCTLDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTLDefinition }
     * 
     * 
     */
    public List<CTLDefinition> getCTLDefinitions() {
        if (ctlDefinitions == null) {
            ctlDefinitions = new ArrayList<CTLDefinition>();
        }
        return this.ctlDefinitions;
    }

}
