//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.22 at 05:26:27 PM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rebecalang.org/compiler/modelcompiler/corerebecaexpression", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.rebecalang.compiler.propertycompiler.generalrebeca.objectmodel;
